# --- MLFLOW ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::040175285118:role/S3ArtifactsAccessRole
    spec:
      serviceAccountName: mlops-sa
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command: ["mlflow", "server"]
          args:
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--backend-store-uri=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):5432/$(POSTGRES_DB)"
            - "--default-artifact-root=s3://tu-bucket-produccion-mlflow-streaming"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mlops-config
            - secretRef:
                name: mlops-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops-env
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---
# --- STREAMING CONSUMER ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-consumer
  namespace: mlops-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-consumer
  template:
    metadata:
      labels:
        app: streaming-consumer
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::040175285118:role/S3ArtifactsAccessRole
    spec:
      serviceAccountName: mlops-sa
      containers:
        - name: consumer
          image: 040175285118.dkr.ecr.us-east-1.amazonaws.com/predictive-maintenance-mlops-streaming:latest
          imagePullPolicy: Always
          command: ["python", "streaming/kafka_consumer.py"]
          envFrom:
            - configMapRef:
                name: mlops-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
# --- API (FastAPI) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-maintenance-api
  namespace: mlops-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::040175285118:role/S3ArtifactsAccessRole
    spec:
      serviceAccountName: mlops-sa
      containers:
        - name: api
          image: 040175285118.dkr.ecr.us-east-1.amazonaws.com/predictive-maintenance-mlops-streaming:latest
          imagePullPolicy: Always
          command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: mlops-config
---
apiVersion: v1
kind: Service
metadata:
  name: predictive-maintenance-api
  namespace: mlops-env
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000